version: '2'
services:
  gem:
    build:
      context: .
    volumes:
      - .:/var/gem
    ports:
      - '3000:3000'
    depends_on:
      - db
    entrypoint: ./bin/run_dummy_app
  db:
    image: postgres:9.6.2-alpine
    ports:
      - '5432'
    volumes:
      - postgres96:/var/lib/postgresql/data
volumes:
  postgres96:
