version: '2'

services:
  gem:
    build:
      context: .
    volumes:
      - .:/var/gem
    depends_on:
      - db
  db:
    image: postgres:9.6.2-alpine
    ports:
      - '5432'
    volumes:
      - postgres96:/var/lib/postgresql/data
volumes:
  postgres96:
