default: &default
  adapter: postgresql
  encoding: unicode
  database: rate_limiter-dev

development:
  <<: *default
  database: rate_limiter-dev
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:@db:5432/rate_limiter_development") %>

test:
  <<: *default
  database: rate_limiter-test
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:@db:5432/rate_limiter_test") %>
